spring:
  application:
    name: uaa-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
server:
  port: 9999
  context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    password: password
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/