spring:
  application:
    name: service-Resources
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    
server:
  port: 7777
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      user-info-uri: ${auth-server}/me

logging:
  level:
    org.springframework.security: DEBUG
    
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1000
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
auth-server: http://localhost:9999/uaa
